In [1]:
import pandas as pd
import numpy as np
from matplotlib  import pyplot as plt
from collections import Counter
import os
print(os.getcwd())

C:\Users\sri\python


In [2]:
os.chdir("C://Users/sri/Documents")
print(os.getcwd())

C:\Users\sri\Documents


In [3]:
ch=pd.read_csv("Churn.csv")
ch.head()

AccountLength  VMailMessage  DayMins  EveMins  NightMins  IntlMins  \
0            128            25    265.1    197.4      244.7      10.0   
1            107            26    161.6    195.5      254.4      13.7   
2            137             0    243.4    121.2      162.6      12.2   
3             84             0    299.4     61.9      196.9       6.6   
4             75             0    166.7    148.3      186.9      10.1   

   CustServCalls  Churn  IntlPlan  VMailPlan  ...  DayCharge  EveCalls  \
0              1      0         0          1  ...      45.07        99   
1              1      0         0          1  ...      27.47       103   
2              0      0         0          0  ...      41.38       110   
3              2      0         1          0  ...      50.90        88   
4              3      0         1          0  ...      28.34       122   

   EveCharge  NightCalls  NightCharge  IntlCalls  IntlCharge  State AreaCode  \
0      16.78          91        11.01          3        2.70     KS      415   
1      16.62         103        11.45          3        3.70     OH      415   
2      10.30         104         7.32          5        3.29     NJ      415   
3       5.26          89         8.86          7        1.78     OH      408   
4      12.61         121         8.41          3        2.73     OK      415   

      Phone  
0  382-4657  
1  371-7191  
2  358-1921  
3  375-9999  
4  330-6626  

[5 rows x 21 columns]

In [4]:
ch.shape

(3333, 21)

In [5]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
AccountLength    3333 non-null int64
VMailMessage     3333 non-null int64
DayMins          3333 non-null float64
EveMins          3333 non-null float64
NightMins        3333 non-null float64
IntlMins         3333 non-null float64
CustServCalls    3333 non-null int64
Churn            3333 non-null int64
IntlPlan         3333 non-null int64
VMailPlan        3333 non-null int64
DayCalls         3333 non-null int64
DayCharge        3333 non-null float64
EveCalls         3333 non-null int64
EveCharge        3333 non-null float64
NightCalls       3333 non-null int64
NightCharge      3333 non-null float64
IntlCalls        3333 non-null int64
IntlCharge       3333 non-null float64
State            3333 non-null object
AreaCode         3333 non-null int64
Phone            3333 non-null object
dtypes: float64(8), int64(11), object(2)
memory usage: 546.9+ KB


In [6]:
ch.isnull().sum()

AccountLength    0
VMailMessage     0
DayMins          0
EveMins          0
NightMins        0
IntlMins         0
CustServCalls    0
Churn            0
IntlPlan         0
VMailPlan        0
DayCalls         0
DayCharge        0
EveCalls         0
EveCharge        0
NightCalls       0
NightCharge      0
IntlCalls        0
IntlCharge       0
State            0
AreaCode         0
Phone            0
dtype: int64

In [7]:
ch.columns.values

array(['AccountLength', 'VMailMessage', 'DayMins', 'EveMins', 'NightMins',
       'IntlMins', 'CustServCalls', 'Churn', 'IntlPlan', 'VMailPlan',
       'DayCalls', 'DayCharge', 'EveCalls', 'EveCharge', 'NightCalls',
       'NightCharge', 'IntlCalls', 'IntlCharge', 'State', 'AreaCode',
       'Phone'], dtype=object)

In [8]:
x=ch.select_dtypes(include=['category',object]).columns
print(len(x))
print(x)

2
Index(['State', 'Phone'], dtype='object')


In [9]:
for i in ch.columns:
    print(i)
    print(Counter(ch[i]))
    print(ch[i].describe())

AccountLength
Counter({105: 43, 87: 42, 93: 40, 101: 40, 90: 39, 95: 38, 86: 38, 116: 37, 100: 37, 107: 36, 99: 36, 112: 36, 120: 35, 127: 35, 123: 35, 106: 34, 122: 34, 88: 34, 94: 33, 80: 33, 103: 33, 92: 33, 75: 32, 117: 32, 74: 32, 73: 32, 98: 32, 64: 32, 119: 32, 113: 32, 121: 31, 78: 31, 115: 31, 85: 30, 130: 30, 68: 30, 108: 30, 111: 29, 97: 29, 110: 29, 125: 28, 104: 28, 91: 28, 124: 28, 84: 27, 132: 27, 63: 27, 67: 27, 96: 26, 70: 26, 148: 26, 89: 26, 129: 26, 137: 25, 72: 25, 136: 25, 81: 25, 138: 25, 82: 25, 131: 25, 118: 24, 76: 24, 83: 24, 109: 24, 114: 23, 79: 23, 102: 23, 128: 22, 141: 22, 77: 22, 65: 21, 149: 21, 126: 21, 66: 21, 134: 21, 62: 20, 57: 19, 55: 19, 139: 19, 71: 19, 147: 18, 161: 18, 135: 18, 59: 18, 52: 18, 146: 18, 54: 17, 60: 17, 155: 17, 61: 17, 56: 17, 48: 17, 133: 17, 69: 17, 143: 16, 58: 16, 142: 15, 50: 15, 144: 15, 140: 15, 51: 15, 36: 14, 160: 14, 46: 14, 41: 14, 53: 14, 157: 13, 163: 13, 145: 13, 45: 13, 166: 13, 37: 13, 43: 12, 151: 12, 152: 12,

Counter({9.66: 15, 9.45: 15, 8.47: 14, 8.88: 14, 7.69: 13, 8.64: 12, 9.14: 11, 7.15: 11, 8.57: 11, 10.49: 11, 9.32: 11, 9.23: 11, 10.35: 11, 10.8: 11, 9.48: 11, 9.18: 10, 9.71: 10, 9.4: 10, 8.15: 10, 9.63: 10, 8.61: 10, 8.21: 10, 9.09: 10, 9.27: 10, 7.14: 10, 9.97: 10, 9.65: 10, 9.17: 10, 10.22: 10, 7.34: 9, 7.79: 9, 10.29: 9, 7.83: 9, 8.59: 9, 7.52: 9, 8.71: 9, 8.78: 9, 8.93: 9, 8.09: 9, 9.91: 9, 9.64: 9, 6.48: 9, 10.68: 9, 8.73: 9, 7.92: 9, 8.01: 9, 8.86: 8, 8.82: 8, 7.46: 8, 10.25: 8, 10.08: 8, 11.88: 8, 8.1: 8, 9.76: 8, 10.23: 8, 11.12: 8, 9.36: 8, 11.7: 8, 10.17: 8, 8.74: 8, 10.13: 8, 11.07: 8, 10.42: 8, 7.62: 8, 10.81: 8, 8.5: 8, 7.6: 8, 9.56: 8, 10.06: 8, 8.19: 8, 10.11: 8, 8.66: 8, 9.26: 8, 8.2: 8, 9.7: 8, 8.83: 8, 11.51: 8, 8.67: 8, 9.57: 7, 8.68: 7, 8.18: 7, 8.53: 7, 6.44: 7, 10.28: 7, 8.52: 7, 6.69: 7, 12.15: 7, 11.39: 7, 10.86: 7, 7.65: 7, 6.97: 7, 7.88: 7, 11.55: 7, 6.93: 7, 11.66: 7, 10.65: 7, 9.05: 7, 10.85: 7, 8.12: 7, 11.49: 7, 11.25: 7, 11.03: 7, 8.91: 7, 9.79: 7, 8.1

In [10]:
ch.AccountLength.describe()

count    3333.000000
mean      101.064806
std        39.822106
min         1.000000
25%        74.000000
50%       101.000000
75%       127.000000
max       243.000000
Name: AccountLength, dtype: float64

In [11]:
cont = list[("AccountLength","VMailMessage","DayMins","EveMins","NightMin",
             "IntlMins","DayCalls","DayCharge","EveCalls",
              "EveCharge","NightCalls","NightCharge","IntlCalls","IntlCharge")]
print(cont.shape)

TypeError: 'type' object is not subscriptable

In [ ]:
cat =list[("CustServCalls","IntlPlan","VMailPlan","State","AreaCode")]

In [12]:
# apply chi square between area code and churn
table = pd.crosstab(ch.CustServCalls,ch.Churn)
print(table)
from scipy.stats import chi2_contingency
from scipy.stats import chi2
chisquare, p, dof, expected = chi2_contingency(table)
print('dof: ', dof)
print('chisquare: ', chisquare)
print('p: ' , p)
print('expected: ', expected)
# apply chi square between area code and churn
table = pd.crosstab(ch.IntlPlan,ch.Churn)
print(table)
from scipy.stats import chi2_contingency
from scipy.stats import chi2
chisquare, p, dof, expected = chi2_contingency(table)
print('dof: ', dof)
print('chisquare: ', chisquare)
print('p: ' , p)
print('expected: ', expected)

Churn             0    1
CustServCalls           
0               605   92
1              1059  122
2               672   87
3               385   44
4                90   76
5                26   40
6                 8   14
7                 4    5
8                 1    1
9                 0    2
dof:  9
chisquare:  342.67460696087505
p:  2.243376519451563e-68
expected:  [[5.95994599e+02 1.01005401e+02]
 [1.00985599e+03 1.71144014e+02]
 [6.49009901e+02 1.09990099e+02]
 [3.66831683e+02 6.21683168e+01]
 [1.41944194e+02 2.40558056e+01]
 [5.64356436e+01 9.56435644e+00]
 [1.88118812e+01 3.18811881e+00]
 [7.69576958e+00 1.30423042e+00]
 [1.71017102e+00 2.89828983e-01]
 [1.71017102e+00 2.89828983e-01]]
Churn        0    1
IntlPlan           
0         2664  346
1          186  137
dof:  1
chisquare:  222.5657566499376
p:  2.4931077033159556e-50
expected:  [[2573.80738074  436.19261926]
 [ 276.19261926   46.80738074]]


In [13]:
# apply chi square between area code and churn
table = pd.crosstab(ch.VMailPlan,ch.Churn)
print(table)
from scipy.stats import chi2_contingency
from scipy.stats import chi2
chisquare, p, dof, expected = chi2_contingency(table)
print('dof: ', dof)
print('chisquare: ', chisquare)
print('p: ' , p)
print('expected: ', expected)

Churn         0    1
VMailPlan           
0          2008  403
1           842   80
dof:  1
chisquare:  34.13166001075673
p:  5.15063965903898e-09
expected:  [[2061.61116112  349.38883888]
 [ 788.38883888  133.61116112]]


In [14]:
# apply chi square between area code and churn
table = pd.crosstab(ch.State,ch.Churn)
##print(table)
from scipy.stats import chi2_contingency
from scipy.stats import chi2
chisquare, p, dof, expected = chi2_contingency(table)
print('dof: ', dof)
#print('chisquare: ', chisquare)
print('p: ' , p)
#print('expected: ', expected)

dof:  50
p:  0.002296221552011188


In [15]:
print(np.corrcoef(ch.DayMins,ch.DayCalls))
print(np.corrcoef(ch.DayMins,ch.DayCharge))
print(np.corrcoef(ch.EveMins,ch.EveCalls))
print(np.corrcoef(ch.EveMins,ch.EveCharge))
print(np.corrcoef(ch.NightMins,ch.NightCalls))
print(np.corrcoef(ch.NightMins,ch.NightCharge))
print(np.corrcoef(ch.IntlMins,ch.IntlCalls))
print(np.corrcoef(ch.IntlMins,ch.IntlCharge))
print(np.corrcoef(ch.IntlCalls,ch.IntlCharge))
print(np.corrcoef(ch.NightCalls,ch.NightCharge))
print(np.corrcoef(ch.EveCalls,ch.EveCharge))
print(np.corrcoef(ch.DayCalls,ch.DayCharge))

[[1.         0.00675041]
 [0.00675041 1.        ]]
[[1.         0.99999995]
 [0.99999995 1.        ]]
[[ 1.         -0.01143011]
 [-0.01143011  1.        ]]
[[1.         0.99999978]
 [0.99999978 1.        ]]
[[1.         0.01120386]
 [0.01120386 1.        ]]
[[1.         0.99999921]
 [0.99999921 1.        ]]
[[1.         0.03230388]
 [0.03230388 1.        ]]
[[1.         0.99999274]
 [0.99999274 1.        ]]
[[1.         0.03237215]
 [0.03237215 1.        ]]
[[1.         0.01118782]
 [0.01118782 1.        ]]
[[ 1.         -0.01142289]
 [-0.01142289  1.        ]]
[[1.         0.00675296]
 [0.00675296 1.        ]]


In [16]:
# apply chi square between area code and churn
table = pd.crosstab(ch.AreaCode,ch.Churn)
print(table)
from scipy.stats import chi2_contingency
from scipy.stats import chi2
chisquare, p, dof, expected = chi2_contingency(table)
print('dof: ', dof)
print('chisquare: ', chisquare)
print('p: ' , p)
print('expected: ', expected)

Churn        0    1
AreaCode           
408        716  122
415       1419  236
510        715  125
dof:  2
chisquare:  0.17754069117425395
p:  0.9150556960243712
expected:  [[ 716.56165617  121.43834383]
 [1415.16651665  239.83348335]
 [ 718.27182718  121.72817282]]


In [17]:
# Create file with dependent 
chY = pd.DataFrame(ch,columns=['Churn'])
print(chY.shape)
print(chY.head())

(3333, 1)
   Churn
0      0
1      0
2      0
3      0
4      0


In [18]:
ch.columns

Index(['AccountLength', 'VMailMessage', 'DayMins', 'EveMins', 'NightMins',
       'IntlMins', 'CustServCalls', 'Churn', 'IntlPlan', 'VMailPlan',
       'DayCalls', 'DayCharge', 'EveCalls', 'EveCharge', 'NightCalls',
       'NightCharge', 'IntlCalls', 'IntlCharge', 'State', 'AreaCode', 'Phone'],
      dtype='object')

In [19]:
# Create file with independent 
# ignoring day min, eve mings, night mins, int mins
import copy
chX = copy.copy(ch)
print(id(ch))
print(id(chX))
chX.drop(columns=['DayMins', 'EveMins', 'NightMins','IntlMins','DayCalls','EveCalls','NightCalls','IntlCalls',
                     'Churn','Phone'],
            inplace=True)
print(chX.shape)

1983841239432
1983852833736
(3333, 11)


In [20]:
# splitting the data into Train and Test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(chX, chY,
                                                    test_size = 0.20,
                                                    random_state = 0)
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)
print(Y_train[0:10])

(2666, 11)
(2666, 1)
(667, 11)
(667, 1)
      Churn
1460      0
2000      0
666       0
2962      0
2773      1
961       0
3079      1
1120      0
962       0
2293      0


In [21]:
# extract only continuous columns
ContColumns = list(['AccountLength', 'VMailMessage', 'CustServCalls',
                     'DayCharge','EveCharge',
                     'NightCharge',  'IntlCharge'])
X_train_cont = pd.DataFrame(X_train,columns=ContColumns)
print(X_train_cont.shape)
X_test_cont = pd.DataFrame(X_test,columns=ContColumns)
print(X_test_cont.shape)

(2666, 7)
(667, 7)


In [22]:
# apply sclaing on continuous variables
from sklearn.preprocessing import MinMaxScaler
MMS = MinMaxScaler()
X_train_cont2 = MMS.fit_transform(X_train_cont)
X_test_cont2 = MMS.transform(X_test_cont)
# convert X_train3 as dataframe
X_train_cont3 = pd.DataFrame(X_train_cont2)
X_test_cont3 = pd.DataFrame(X_test_cont2)

In [23]:
# extract only categorical columns
CatColumns = list(['IntlPlan','VMailPlan','State','AreaCode'])
X_train_cat = pd.DataFrame(X_train,columns=CatColumns)
print(X_train_cat.shape)
X_test_cat = pd.DataFrame(X_test,columns=CatColumns)
print(X_test_cat.shape)

(2666, 4)
(667, 4)


In [24]:
# lable encoding for strings
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train_cat.State = le.fit_transform(X_train_cat.State)
X_test_cat.State = le.transform(X_test_cat.State)
print((np.unique(X_train_cat.State)))
print(len(np.unique(X_train_cat.State)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
51


In [25]:
# apply one hot encoding on state and area
from sklearn.preprocessing import OneHotEncoder
# columns 2,3represent state and area code
categories = np.array([2,3])     
OHE = OneHotEncoder(categories='auto', sparse = False, handle_unknown = 'error')
X_train_cat2 = OHE.fit_transform(X_train_cat)
print(X_train_cat2.shape)
X_test_cat2 = OHE.transform(X_test_cat)
print(X_test_cat2.shape)
# convert array as dataframe
X_train_cat3 = pd.DataFrame(X_train_cat2)
print(X_train_cat3.index)
print(X_train_cat3.shape)
X_test_cat3 = pd.DataFrame(X_test_cat2)
print(X_test_cat3.shape)

(2666, 58)
(667, 58)
RangeIndex(start=0, stop=2666, step=1)
(2666, 58)
(667, 58)


In [26]:
# merge scaled continuous and onehotencoded categorical data
X_train_final = pd.concat([X_train_cont3,X_train_cat3],axis=1,join='outer',ignore_index=True)
X_test_final = pd.concat([X_test_cont3,X_test_cat3],axis=1,join='outer',ignore_index=True)
print(X_train_final.shape)
print(X_test_final.shape)

(2666, 65)
(667, 65)


In [1]:
# logistic model
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression(class_weight = 'balanced',solver='saga',
                         max_iter=500,penalty = 'l1')
parms = {'C': [0.05,0.2,0.5,1,2]} 
# perform grid search with cross validation
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = lgr,param_grid = parms, scoring = 'f1_macro',
                  cv=5,refit=True,return_train_score = True,verbose=1)
CV_LR=CV.fit(X_train_final,Y_train.Churn)

NameError: name 'X_train_final' is not defined

In [28]:
CVResults = pd.DataFrame(CV.cv_results_)
CVResults.to_excel('CVResutls_Logistic.xlsx')

In [29]:
print(CV.best_estimator_.coef_)
print(CV.best_estimator_.intercept_)

[[ 6.45803933e-05  0.00000000e+00  4.70834251e+00  4.23196860e+00
   1.46201304e+00  5.76248148e-01  3.94151811e-01 -1.94084664e+00
   2.71378480e-01  2.73250502e-01 -4.91294106e-01  0.00000000e+00
  -1.30012090e-01  0.00000000e+00 -2.60554210e-01  5.21058674e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00 -8.09274644e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.79187164e-02
   2.97925954e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   5.96786290e-01  7.43506591e-01 -7.16099113e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  5.76531210e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  2.10762460e-02  0.00000000e+00  6.92495524e-01
   0.00000000e+00  0.00000000e+00  4.71934293e-02  0.00000000e+00
  -2.22274306e-01 -3.66205148e-01  1.25158485e-01  0.00000000e+00
   0.00000

In [30]:
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test_final)
print(predictTest[0:10])
PredictProb = CV.predict_proba(X_test_final)
print(PredictProb[0:10])
PProb = pd.DataFrame(PredictProb)

[1 0 1 0 1 1 1 0 1 1]
[[0.16039985 0.83960015]
 [0.8932445  0.1067555 ]
 [0.3628783  0.6371217 ]
 [0.73086235 0.26913765]
 [0.03213422 0.96786578]
 [0.03409509 0.96590491]
 [0.23050612 0.76949388]
 [0.75122639 0.24877361]
 [0.36055702 0.63944298]
 [0.23459869 0.76540131]]


In [31]:
# generate confusion matrix
# import confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(Y_test,predictTest))
print (classification_report(Y_test,predictTest))

[[439 140]
 [ 19  69]]
              precision    recall  f1-score   support

           0       0.96      0.76      0.85       579
           1       0.33      0.78      0.46        88

    accuracy                           0.76       667
   macro avg       0.64      0.77      0.66       667
weighted avg       0.88      0.76      0.80       667



In [37]:
from sklearn.model_selection import RandomizedSearchCV

In [33]:
def confusion_m(model, title):
    cm = confusion_matrix(y_test, model.predict(X_test_final))
    f, ax = plt.subplots(figsize = (8, 6))
    sns.heatmap(cm, annot = True, linewidths = 0.5, color = 'red', fmt = '.0f', ax = ax)
    plt.xlabel('y_predicted')
    plt.ylabel('y_true')
    plt.title(title)
    plt.show()

def feature_importance(model, title):
    dataframe = pd.DataFrame(model, X_train.columns).reset_index()
    dataframe = dataframe.rename(columns = {'index':'features', 0:'coefficients'})
    dataframe = dataframe.sort_values(by = 'coefficients', ascending = False)
    plt.figure(figsize=(13,10), dpi= 60)
    ax = sns.barplot(x = 'coefficients', y = 'features', data = dataframe ,palette = 'husl')
    plt.title(title, fontsize = 20)

In [47]:
#5.1 Logistic Regression
lr = LogisticRegression(random_state = 12345)
parameters_lr = {'C': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 3, 5, 7, 10, 15, 20, 25, 30, 50], 
                 'penalty':['l1', 'l2', 'elasticnet'],
                 'solver':['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
                 'class_weight': [1, 3, 10],
                 'max_iter': [200, 500, 800, 1000, 2000]}
search_lr = RandomizedSearchCV(lr, parameters_lr, cv=5, scoring = 'accuracy', n_jobs = -1, random_state = 12345)
search_lr.fit(X_train,Y_train)
best_lr = search_lr.best_estimator_
predict_lr = best_lr.predict(X_valid)
auc_lr = cross_val_score(best_lr, X_valid, y_valid, scoring = 'roc_auc', cv = 10, n_jobs = -1)
acc_lr = cross_val_score(best_lr, X_valid, y_valid, scoring = 'accuracy', cv = 10, n_jobs = -1)
print('AUC-ROC for Logistic Regression on validation dataset:', sum(auc_lr)/len(auc_lr))
print('Accuracy for Logistic Regression on validation dataset:', sum(acc_lr)/len(acc_lr))
#AUC-ROC for Logistic Regression on validation dataset: 0.826001221001221
#Accuracy for Logistic Regression on validation dataset: 0.7719367588932806
confusion_m(best_lr, 'Confusion matrix for Logistic Regression')
feature_importance(best_lr.coef_[0], 'Feature importance for Logistic Regression')



ValueError: could not convert string to float: 'NC'

In [31]:
from sklearn import metrics
print(metrics.accuracy_score(Y_test,predictTest))

0.7616191904047976


In [32]:
# DecisionTree Classifier
from sklearn.tree import DecisionTreeClassifier
CART = DecisionTreeClassifier(class_weight='balanced')
# build grid search parameters
parms = {'min_samples_split': [10,8,5], 
         'min_samples_leaf': [2,3,5],
         'min_impurity_decrease' :[0.1,0.5],
         'max_depth':[2,3,4]} 
#parms = {'max_depth':[2,3,4,5,6,7,8,9,10]} 
#parms = {'min_impurity_decrease':[0.01,0.05,0.10]}
# grid search
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = CART,param_grid = parms, 
                  scoring = 'f1_macro',
                  cv=3,refit=True,
                  return_train_score = True,verbose=1,n_jobs=1)
CV.fit(X_train_final,Y_train.Churn)

Fitting 3 folds for each of 54 candidates, totalling 162 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', averag

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classificat

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classificat

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classificat

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classificat

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classificat

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classificat

C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
[Parallel(n_jobs=1)]: Done 162 out of 162 | elapsed:    4.3s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight='balanced',
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=1,
             param_grid={'max_depth': [2, 3, 4],
                         'min_impurity_decrease': [0.1, 0.5],
                      

In [47]:
#print(CV.best_estimator_.coef_)
#print(CV.best_estimator_.intercept_)
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test_final)
print(predictTest[0:10])
PredictProb = CV.predict_proba(X_test_final)
print(PredictProb[0:10])
PProb = pd.DataFrame(PredictProb)

[1 0 0 0 1 1 0 0 0 1]
[[0.28434839 0.71565161]
 [0.87708468 0.12291532]
 [0.86011999 0.13988001]
 [0.86011999 0.13988001]
 [0.0572294  0.9427706 ]
 [0.10744318 0.89255682]
 [0.52774136 0.47225864]
 [0.86011999 0.13988001]
 [0.85055173 0.14944827]
 [0.27268495 0.72731505]]


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


In [36]:
# generate confusion matrix
# import confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(Y_test,predictTest))
print (classification_report(Y_test,predictTest))
from sklearn import metrics
print(metrics.accuracy_score(Y_test,predictTest))

[[579   0]
 [ 88   0]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93       579
           1       0.00      0.00      0.00        88

    accuracy                           0.87       667
   macro avg       0.43      0.50      0.46       667
weighted avg       0.75      0.87      0.81       667

0.8680659670164917


C:\Users\sri\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
# KNN
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(algorithm = 'auto')
parms = {'n_neighbors': [3,5,7,9],
          'weights' : ['uniform','distance']} 
# perform grid search with cross validation
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = KNN,param_grid = parms, 
                  scoring = 'f1_macro',
                  cv=3,refit=True,return_train_score = True,verbose=1,
                  n_jobs=-1)
CV.fit(X_train_final,Y_train.Churn)

Fitting 3 folds for each of 8 candidates, totalling 24 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed:   21.6s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=-1,
             param_grid={'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='f1_macro', verbose=1)

In [39]:
#print(CV.best_estimator_.coef_)
#print(CV.best_estimator_.intercept_)
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test_final)
print(predictTest[0:10])
PredictProb = CV.predict_proba(X_test_final)
print(PredictProb[0:10])
PProb = pd.DataFrame(PredictProb)

[0 0 0 0 1 1 0 0 0 0]
[[0.81230627 0.18769373]
 [1.         0.        ]
 [1.         0.        ]
 [1.         0.        ]
 [0.33338797 0.66661203]
 [0.33327815 0.66672185]
 [0.77181463 0.22818537]
 [1.         0.        ]
 [1.         0.        ]
 [0.72226791 0.27773209]]


In [40]:
# generate confusion matrix
# import confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(Y_test,predictTest))
print (classification_report(Y_test,predictTest))
from sklearn import metrics
print(metrics.accuracy_score(Y_test,predictTest))

[[545  34]
 [ 67  21]]
              precision    recall  f1-score   support

           0       0.89      0.94      0.92       579
           1       0.38      0.24      0.29        88

    accuracy                           0.85       667
   macro avg       0.64      0.59      0.60       667
weighted avg       0.82      0.85      0.83       667

0.848575712143928


In [41]:
# SVM
from sklearn.svm import SVC
SVM = SVC(class_weight='balanced',degree=2,probability=True)

# build grid search parameters
parms = {'C': [0.1,0.5,0.8],
         'gamma':[0.1,0.5,0.8],
         'kernel': ["rbf","sigmoid"]}
# perform grid search
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = SVM,param_grid = parms, scoring = 'f1_macro',
                  cv=3,refit=True,return_train_score = True,verbose=1)
CV.fit(X_train_final,Y_train.Churn)

Fitting 3 folds for each of 18 candidates, totalling 54 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  54 out of  54 | elapsed:  4.0min finished


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight='balanced',
                           coef0=0.0, decision_function_shape='ovr', degree=2,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 0.5, 0.8], 'gamma': [0.1, 0.5, 0.8],
                         'kernel': ['rbf', 'sigmoid']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring='f1_macro', verbose=1)

In [43]:
#print(CV.best_estimator_.coef_)
#print(CV.best_estimator_.intercept_)
# Preidct on Test data and check the confusion matrix
predictTest = CV.predict(X_test_final)
print(predictTest[0:10])
PredictProb = CV.predict_proba(X_test_final)
print(PredictProb[0:10])
PProb = pd.DataFrame(PredictProb)

[1 0 0 0 1 1 1 0 1 1]
[[0.5        0.5       ]
 [0.95860125 0.04139875]
 [0.86660452 0.13339548]
 [0.93615476 0.06384524]
 [0.37570794 0.62429206]
 [0.31205254 0.68794746]
 [0.52208026 0.47791974]
 [0.8429311  0.1570689 ]
 [0.73705848 0.26294152]
 [0.6568698  0.3431302 ]]


In [44]:
# generate confusion matrix
# import confusion matrix and classification report
from sklearn.metrics import confusion_matrix, classification_report
print (confusion_matrix(Y_test,predictTest))
print (classification_report(Y_test,predictTest))
from sklearn import metrics
print(metrics.accuracy_score(Y_test,predictTest))

[[458 121]
 [ 25  63]]
              precision    recall  f1-score   support

           0       0.95      0.79      0.86       579
           1       0.34      0.72      0.46        88

    accuracy                           0.78       667
   macro avg       0.65      0.75      0.66       667
weighted avg       0.87      0.78      0.81       667

0.7811094452773614


In [45]:
# Bagging Classifier
# build decision tree object
from sklearn.tree import DecisionTreeClassifier
CART = DecisionTreeClassifier(class_weight='balanced', max_depth = 4)
# build bagging object
from sklearn.ensemble import BaggingClassifier
Bagging = BaggingClassifier(base_estimator = CART, 
                           verbose = 1, oob_score = False,
                            random_state = 1)
# build grid search parameters
parms = {'n_estimators' : [5,10,15],
          'bootstrap':[True,False],
          'max_samples':[0.3,0.6,0.9], 
          'max_features':[1.0]
        }
# grid search
from sklearn.model_selection import GridSearchCV
CV = GridSearchCV(estimator = Bagging,param_grid = parms, scoring = 'f1_macro',
                  cv=3, refit=True,return_train_score = True, verbose=1)
CV.fit(X_train_final,Y_train.Churn)

Fitting 3 folds for each of 18 candidates, totalling 54 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_j

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_j

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished
[Parallel(n_jobs=1)]: Us

GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight='balanced',
                                                                               criterion='gini',
                                                                               max_depth=4,
                                                                               max_features=None,
                                                                               max_leaf_nodes=None,
                                                                               min_impurity_decrease=0.0,
                                                                               min_impurity_split=None,
                                                                               min_samples_leaf=1,
                                                                               min_samples_split=2,
                                                